Add windows hypervisor support
- Tested with Workstation 14
- Changed all path separators to be platform agnostic
- Uses installer/main.go return hypervisor CPI location (and optionally install it)

diff --git a/jobs/vmrun_cpi/templates/cpi.erb b/jobs/vmrun_cpi/templates/cpi.erb
--- a/jobs/vmrun_cpi/templates/cpi.erb
+++ b/jobs/vmrun_cpi/templates/cpi.erb
@@ -21,44 +21,43 @@ fi
   username="<%= p('vmrun.ssh_tunnel.username') %>"
   port="<%= p('vmrun.ssh_tunnel.port') %>"
   hypervisor_platform="<%= p('vmrun.ssh_tunnel.platform') %>"
-  hypervisor_cpi_prefix="$BOSH_PACKAGES_DIR/vmrun_cpi/bin/cpi"
-  private_key_file=$BOSH_JOBS_DIR/vmrun_cpi/config/ssh_tunnel_key
-
+  director_platform=$(uname | tr '[:upper:]' '[:lower:]')
+  package_installer_path="${BOSH_PACKAGES_DIR}/vmrun_cpi/bin/installer-${director_platform}"
+  private_key_file=${BOSH_JOBS_DIR}/vmrun_cpi/config/ssh_tunnel_key
+  
+  # CPI config.json content is base64 encoded so it can be passed as SSH_ORIGINAL_COMMAND to ssh authorized_keys command
+  # - use perl for cross-platform base64 compatibility
+  encoded_config="$(cat $BOSH_JOBS_DIR/vmrun_cpi/config/cpi.json | perl -MMIME::Base64 -0777 -ne 'print encode_base64($_, q())')"
+  
   echo "CPI: using ssh-tunnel env: {host: $host, username: $username, port: $port, private_key_file: $private_key_file} " >> $err_log
 
   if [ -w $BOSH_JOBS_DIR/vmrun_cpi/config ]; then
     chmod 0600 $private_key_file
   fi
 
-
   echo "CPI: set permissions on key file" >> $err_log
 
-  # On hypervisor (has vm-store dir), ensure SSH authorized_host contains CPI command and pubkey
-  if [ -d "<%= p('vmrun.vm_store_path') %>" ]; then
-    public_key=$(ssh-keygen -y -f $private_key_file)
-
-    # CPI config.json content in the entire SSH_ORIGINAL_COMMAND is base64 decoded and passed as fifo
-    # - use perl for cross-platform base64 compatibility and to avoid command jailbreaking
-    auth_key_entry="restrict,command=\"$hypervisor_cpi_prefix-$hypervisor_platform \${SSH_ORIGINAL_COMMAND#* }\" $public_key $username@localhost"
-    if [ -f ~/.ssh/authorized_keys ] && grep -q -e "$hypervisor_cpi_prefix-$hypervisor_platform.*$public_key" ~/.ssh/authorized_keys; then
-      echo "CPI: command is correctly set in authorized_key:\n---\n$auth_key_entry\n---" >> $err_log
-      echo > /dev/null
-    else
-      echo "CPI: command is correctly set in authorized_key:\n---\n$auth_key_entry\n---" >> $err_log
-      echo
-      echo --------------------------
-      echo "add to your ~/.ssh/authorized_keys:"
-      echo "$auth_key_entry"
-      echo --------------------------
-      echo
-      exit 1
-    fi
+  # Lookup path for hypervisor CPI (installs if vm-store dir to find it later)
+  hypervisor_cpi_path=$("$package_installer_path" -platform $hypervisor_platform -configBase64JSON $encoded_config 2>/dev/null)
+  
+  #Check ssh connectivity and fail with helpful error message
+  if echo | grep -q "config" <(ssh -q -i $private_key_file -p $port -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey $username@$host "$hypervisor_cpi_path -h" 2>&1); then
+    echo "CPI: ssh connected successfully" >> $err_log
+  else
+    # CPI cpi args are passed the last args of SSH_ORIGINAL_COMMAND
+    public_key=$(echo | ssh-keygen -y -f $private_key_file)
+    auth_key_entry="restrict,command=\"$hypervisor_cpi_path \${SSH_ORIGINAL_COMMAND#* }\" $public_key $username@localhost"
+    echo "CI: ssh connection failed. Command not set correctly in authorized_key:\n---\n$auth_key_entry\n---" >> $err_log
+    echo
+    echo --------------------------
+    echo "add to your ~/.ssh/authorized_keys:"
+    echo "$auth_key_entry"
+    echo --------------------------
+    echo
+    exit 1
   fi
-
-  # CPI config.json content is gzip + base64 encoded so it can be passed as SSH_ORIGINAL_COMMAND to ssh authorized_keys command
-  # - use perl for cross-platform base64 compatibility
-  configEncoded="$(cat $BOSH_JOBS_DIR/vmrun_cpi/config/cpi.json | base64)"
-  exec ssh -q -i $private_key_file -p $port -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey $username@$host "$hypervisor_cpi_prefix-$hypervisor_platform -configBase64JSON $configEncoded" 2>> $err_log <&0
+  
+  exec ssh -q -i $private_key_file -p $port -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey $username@$host "$hypervisor_cpi_path -configBase64JSON $encoded_config" 2>> $err_log <&0
 
 <% end.else do %>
 
